# Generated by Django 4.2.27 on 2025-12-14 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivorceFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='1. When one of our apologies apologizes when our discussions go in a bad direction, the issue does not extend.')),
                ('q2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='2. I know we can ignore our differences, even if things get hard sometimes.')),
                ('q3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='3. When we need it, we can take our discussions with my wife from the beginning and correct it.')),
                ('q4', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='4. When I argue with my wife, it will eventually work for me to contact him.')),
                ('q5', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='5. The time I spent with my wife is special for us.')),
                ('q6', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="6. We don't have time at home as partners.")),
                ('q7', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='7. We are like two strangers who share the same environment at home rather than family.')),
                ('q8', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='8. I enjoy our holidays with my wife.')),
                ('q9', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='9. I enjoy traveling with my wife.')),
                ('q10', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='10. My wife and most of our goals are common.')),
                ('q11', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='11. I think that one day in the future, when I look back, I see that my wife and I are in harmony with each other.')),
                ('q12', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='12. My wife and I have similar values in terms of personal freedom.')),
                ('q13', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='13. My husband and I have similar entertainment.')),
                ('q14', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='14. Most of our goals for people (children, friends, etc.) are the same.')),
                ('q15', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='15. Our dreams of living with my wife are similar and harmonious')),
                ('q16', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="16. We're compatible with my wife about what love should be")),
                ('q17', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='17. We share the same views with my wife about being happy in your life')),
                ('q18', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='18. My wife and I have similar ideas about how marriage should be')),
                ('q19', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='19. My wife and I have similar ideas about how roles should be in marriage')),
                ('q20', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='20. My wife and I have similar values in trust')),
                ('q21', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='21. I know exactly what my wife likes.')),
                ('q22', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="22. I know how my wife wants to be taken care of when she's sick.")),
                ('q23', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="23. I know my wife's favorite food.")),
                ('q24', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='24. I can tell you what kind of stress my wife is facing in her life.')),
                ('q25', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="25. I have knowledge of my wife's inner world.")),
                ('q26', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="26. I know my wife's basic concerns.")),
                ('q27', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="27. I know what my wife's current sources of stress are.")),
                ('q28', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="28. I know my wife's hopes and wishes.")),
                ('q29', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='29. I know my wife very well.')),
                ('q30', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="30. I know my wife's friends and their social relationships.")),
                ('q31', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='31. I feel aggressive when I argue with my wife.')),
                ('q32', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='32. When discussing with my wife, I usually use expressions such as "you always" or "you never".')),
                ('q33', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="33. I can use negative statements about my wife's personality during our discussions.")),
                ('q34', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='34. I can use offensive expressions during our discussions.')),
                ('q35', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='35. I can insult our discussions.')),
                ('q36', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='36. I can be humiliating when we argue.')),
                ('q37', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='37. My argument with my wife is not calm.')),
                ('q38', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="38. I hate my wife's way of bringing it up.")),
                ('q39', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='39. Fights often occur suddenly.')),
                ('q40', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="40. We're just starting a fight before I know what's going on.")),
                ('q41', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='41. When I talk to my wife about something, my calm suddenly breaks.')),
                ('q42', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="42. When I argue with my wife, it only snaps in and I don't say a word.")),
                ('q43', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="43. I'm mostly thirsty to calm the environment a little bit.")),
                ('q44', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="44. Sometimes I think it's good for me to leave home for a while.")),
                ('q45', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="45. I'd rather stay silent than argue with my wife.")),
                ('q46', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="46. Even if I'm right in the argument, I'm thirsty not to upset the other side.")),
                ('q47', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='47. When I argue with my wife, I remain silent because I am afraid of not being able to control my anger.')),
                ('q48', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='48. I feel right in our discussions.')),
                ('q49', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="49. I have nothing to do with what I've been accused of.")),
                ('q50', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="50. I'm not actually the one who's guilty about what I'm accused of.")),
                ('q51', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="51. I'm not the one who's wrong about problems at home.")),
                ('q52', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="52. I wouldn't hesitate to tell her about my wife's inadequacy.")),
                ('q53', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="53. When I discuss it, I remind her of my wife's inadequate issues.")),
                ('q54', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="54. I'm not afraid to tell her about my wife's incompetence.")),
                ('divorce_class', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Class')),
            ],
        ),
    ]
